# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-03 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloreJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=30)),
                ('eiigibility', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=40)),
                ('phonno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HydJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=30)),
                ('eiigibility', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=40)),
                ('phonno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PuneJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=30)),
                ('eiigibility', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=40)),
                ('phonno', models.IntegerField()),
            ],
        ),
    ]
